// AngularDemo/src/app/app.component.ts
import { Component } from '@angular/core';
import {User} from "./model/user.model";
import {UserService} from "./service/user.service";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: [
    './app.component.css'
  ]
})
export class AppComponent {

  users: User[] = [];

  constructor(
    public userService: UserService
  ) { }

  ngOnInit() {
    this.loadUsers();
  }

  loadUsers() {
    return this.userService.getUsers().subscribe((data) => {
      this.users = data;
    });
  }

}

<div class="toolbar" role="banner">
  <img
    width="40"
    alt="Angular Logo"
    src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
  />
  <span>Angular Demo</span>
  <div class="spacer"></div>
</div>

<div class="content" role="main">

  <app-user-table [users]="users" ></app-user-table>

</div>

// ReactDemo/src/components/app/App.tsx
import React, {useEffect, useState} from 'react';
import logo from '../../logo.svg';
import './App.css';
import User from "../../model/User";
import {UserService} from "../../service/UserService";
import UserTable from "../user-table/UserTable";

function App() {
    const [users, setUsers] = useState<User[]>([]);

    useEffect(() => {
        UserService.getUsers().then(setUsers);
    }, []);

    function handleDeleteUser(user: User){
        setUsers(users.filter(u => u.id !== user.id));
    }

    return (
        <div className="app" >
          <div className="toolbar" role="banner" >
            <img
                width="40"
                alt="React Logo"
                src={logo}
            />
            <span>React Demo</span>
            <div className="spacer"/>
          </div>
          <div className="content" role="main">
                <UserTable users={users} onDeleteUser={handleDeleteUser} />
          </div>
        </div>
    );
}

export default App;
